language: node_js

node_js:
  - "stable"

script:
  - npm install
  - npm test
  - npm run build

deploy:
  provider: surge
  domain: waiting-doctor.surge.sh
  skip_cleanup: true
  project: "./build/"

on:
  branch: main
